version: '2'
services:
  graphite:
    image: sitespeedio/graphite
    ports:
      - 2003:2003
      - 8080:80
    volumes:
      - ./graphite-data:/opt/graphite/storage/whisper
      - ./graphite-conf/storage-schemas.conf:/opt/graphite/conf/storage-schemas.conf
      - ./graphite-conf/storage-aggregation.conf:/opt/graphite/conf/storage-aggregation.conf
  grafana:
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./grafana-data:/var/lib/grafana
